"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { AdminCategory } from "@/interfaces/Category";
import type { AdminProject, AdminProjectLink, AdminProjectStatus } from "@/interfaces/Project";
import { getAdminCategories } from "@/components/api/categories";
import { createAdminProject, deleteAdminProject, getAdminProjects, updateAdminProject } from "@/components/api/projects";
import { getApiErrorMessage } from "@/components/api/client";
import { useAdminStorage } from "@/components/hooks/useAdminStorage";
import CategoryMultiSelect from "@/components/admin/CategoryMultiSelect";

type Tab="add"|"collection";
type Form={title:string;myRole:string;started:string;ended:string;medium:string[];status:AdminProjectStatus;images:File[];links:AdminProjectLink[];dynamicFields:{key:string;value:string}[]};
const PROJECT_STATUSES: AdminProjectStatus[] = ["draft", "published", "archived"];
const emptyForm:Form={title:"",myRole:"",started:"",ended:"",medium:[],status:"draft",images:[],links:[],dynamicFields:[]};
const nav=[{label:"Overview",href:"/admin",icon:"grid"},{label:"Categories",href:"/admin/categories",icon:"layers"},{label:"Paintings",href:"/admin/paintings",icon:"image"},{label:"Projects",href:"/admin/projects",icon:"folder"},{label:"Table",href:"/admin/table",icon:"clover"},{label:"Artist",href:"/admin/artist",icon:"user"},{label:"Statistics",href:null,icon:"chart"}] as const;
function formatDateInput(v:string){const d=v.replace(/\D/g,"").slice(0,8);if(d.length<=4)return d;if(d.length<=6)return d.slice(0,4)+"/"+d.slice(4);return d.slice(0,4)+"/"+d.slice(4,6)+"/"+d.slice(6);}
function Icon({type}:{type:(typeof nav)[number]["icon"]}){if(type==="clover")return <span className="admin-nav-clover" aria-hidden="true">☘</span>;if(type==="grid")return <span className="admin-nav-icon admin-nav-icon--grid" aria-hidden="true"><i/><i/><i/><i/></span>;const p:Record<Exclude<(typeof nav)[number]["icon"],"grid"|"clover">,string>={layers:"M12 3 3 8l9 5 9-5-9-5Zm-7.5 8L12 15l7.5-4M4.5 14 12 18l7.5-4M4.5 17 12 21l7.5-4",image:"M4 5.5A1.5 1.5 0 0 1 5.5 4h13A1.5 1.5 0 0 1 20 5.5v13a2 2 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 18.5v-13ZM7.5 16l3-3 2 2 2.5-3 2.5 4H7.5ZM15.5 8.5h.01",folder:"M3.5 6.5h6l2 2h9v9.5a2 2 0 0 1-2 2h-15v-13.5Z",user:"M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm-7 8a7 7 0 0 1 14 0",chart:"M4 19V9m6 10V5m6 14v-7m4 7V3"};return <span className="admin-nav-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d={p[type]}/></svg></span>;}

export default function AdminProjectsPage(){
 const [projects,setProjects]=useState<AdminProject[]>([]),[categories,setCategories]=useState<AdminCategory[]>([]);
 const [form,setForm]=useState<Form>(emptyForm),[editing,setEditing]=useState<AdminProject|null>(null),[tab,setTab]=useState<Tab>("add"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[toast,setToast]=useState<{type:"success"|"error";text:string}|null>(null);
 const {loading:storageLoading,checkMongo,checkBlob,refresh:refreshStorage}=useAdminStorage();
 async function load(){setLoading(true);try{const [p,c]=await Promise.all([getAdminProjects(),getAdminCategories()]);setProjects(p);setCategories(c);}catch(e){setToast({type:"error",text:getApiErrorMessage(e,"Could not load projects.")});}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!toast)return;const t=window.setTimeout(()=>setToast(null),3500);return()=>window.clearTimeout(t)},[toast]);
 function reset(){setEditing(null);setForm(emptyForm);}
 function startEdit(p:AdminProject){setEditing(p);setForm({title:p.title,myRole:p.myRole,started:p.started,ended:p.ended??"",medium:p.medium,status:p.status ?? "draft",images:[],links:p.links.map(x=>({...x})),dynamicFields:Object.entries(p.dynamicFields).map(([key,value])=>({key,value}))});setTab("add");window.scrollTo({top:0,behavior:"smooth"});}
 function addImages(files:File[]){const accepted=files.filter((file)=>["image/jpeg","image/png","image/webp"].includes(file.type)&&file.size>0&&file.size<=4*1024*1024);if(accepted.length!==files.length){setToast({type:"error",text:"Only JPG, PNG and WebP images smaller than 4 MB are accepted."});}setForm(f=>{const total=f.images.reduce((sum,file)=>sum+file.size,0)+accepted.reduce((sum,file)=>sum+file.size,0);if(total>4*1024*1024){setToast({type:"error",text:"Keep the total new project images under 4 MB per save."});return f;}return {...f,images:[...f.images,...accepted]};});}
 function addLink(){setForm(f=>({...f,links:[...f.links,{id:crypto.randomUUID(),title:"",link:""}]}));}
 function addField(){setForm(f=>({...f,dynamicFields:[...f.dynamicFields,{key:"",value:""}]}));}
 async function submit(e:React.FormEvent){e.preventDefault();if(!form.title.trim()||!form.myRole.trim()||!form.started||!form.medium.length||!form.status){setToast({type:"error",text:"Title, role, started, medium and status are required."});return;}if(storageLoading){setToast({type:"error",text:"Checking available storage. Please try again."});return;}const blobBytes=form.images.reduce((sum,file)=>sum+file.size,0);if(!editing&&!form.images.length){setToast({type:"error",text:"At least one project image is required."});return;}if(blobBytes&&!checkBlob(blobBytes)){setToast({type:"error",text:"There is not enough Vercel Blob space for these images."});return;}const estimate=new TextEncoder().encode(JSON.stringify(form)).length+20*1024;if(!checkMongo(estimate)){setToast({type:"error",text:"There is not enough MongoDB space. The safety reserve is kept available."});return;}setSaving(true);try{const payload={...form,dynamicFields:Object.fromEntries(form.dynamicFields.filter(x=>x.key.trim()).map(x=>[x.key.trim(),x.value]))};const result=editing?await updateAdminProject(editing.id,{...payload,images:form.images}):await createAdminProject({...payload,images:form.images});setProjects(p=>editing?p.map(x=>x.id===result.id?result:x):[result,...p]);setToast({type:"success",text:editing?"Project updated successfully.":"Project added successfully."});reset();void refreshStorage();}catch(e){setToast({type:"error",text:getApiErrorMessage(e,"Could not save project.")});}finally{setSaving(false);}}
 async function remove(id:string){if(!confirm("Delete this project?"))return;setSaving(true);try{await deleteAdminProject(id);setProjects(p=>p.filter(x=>x.id!==id));setToast({type:"success",text:"Project deleted."});}catch(e){setToast({type:"error",text:getApiErrorMessage(e,"Could not delete project.")});}finally{setSaving(false);}}

 return <main className="admin-dashboard"><aside className="admin-sidebar"><div><Link href="/" className="admin-sidebar-brand"><span>HAZZART</span><small>ARTIST PORTFOLIO</small></Link><div className="admin-sidebar-divider"/><p className="admin-sidebar-label">WORKSPACE</p><nav className="admin-nav">{nav.map(item=>item.href?<Link key={item.label} href={item.href} className={"admin-nav-item "+(item.label==="Projects"?"is-active":"")}><Icon type={item.icon}/><span>{item.label}</span></Link>:<span key={item.label} className="admin-nav-item is-disabled"><Icon type={item.icon}/><span>{item.label}</span><small>SOON</small></span>)}</nav></div><div className="admin-sidebar-bottom"><div className="admin-user-chip"><span className="admin-user-avatar">A</span><span><strong>Administrator</strong><small>Administrator</small></span></div><form action="/api/admin/auth/logout" method="post"><button className="admin-logout">Log out <span>↗</span></button></form></div></aside>
 <section className="admin-content"><header className="admin-topbar"><Link href="/" className="admin-mobile-brand">HAZZART</Link><span className="admin-topbar-context">ADMIN / PROJECTS</span><Link href="/" className="admin-view-site">View website <span>↗</span></Link></header>
 <div className="admin-main admin-projects-main"><div className="admin-welcome"><div><p className="admin-eyebrow">PROJECTS</p><h1>Build the project archive.</h1><p>Define project details, mediums, status, links and custom metadata.</p></div><button className="admin-round-link" onClick={()=>void load()}>↻</button></div>
 <div className="admin-painting-tabs" role="tablist"><button type="button" className={tab==="add"?"is-active":""} onClick={()=>setTab("add")}>{editing?"EDIT":"ADD"} Project</button><button type="button" className={tab==="collection"?"is-active":""} onClick={()=>setTab("collection")}>VIEW Collection <small>{projects.length}</small></button></div>
 {tab==="add"&&<form className="admin-project-form" onSubmit={submit}><div className="admin-project-heading"><div><p className="admin-card-kicker">{editing?"EDIT PROJECT":"NEW PROJECT"}</p><h2>{editing?editing.title:"Add a project"}</h2></div>{editing&&<button type="button" className="admin-painting-cancel" onClick={reset}>Cancel edit</button>}</div>
 <div className="admin-project-images-section"><div className="admin-painting-section-title"><p className="admin-card-kicker">IMAGES</p><span>{form.images.length} new</span></div><div className="admin-project-image-grid">{form.images.map((file,i)=><div className="admin-project-image-item" key={file.name+"-"+i}><img src={URL.createObjectURL(file)} alt="" /><button type="button" onClick={()=>setForm(f=>({...f,images:f.images.filter((_,n)=>n!==i)}))}>×</button><small>{file.name}</small></div>)}<label className="admin-painting-image-picker admin-project-image-add"><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{addImages(Array.from(e.target.files ?? []));e.currentTarget.value="";}}/><span className="admin-painting-image-placeholder">+</span><span><strong>Add image</strong><small>JPG · PNG · WebP · max 4 MB</small></span></label></div></div><div className="admin-project-grid"><label className="admin-field"><span>Title</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="admin-field"><span>My Role</span><input value={form.myRole} onChange={e=>setForm({...form,myRole:e.target.value})}/></label><label className="admin-field"><span>Started</span><input value={form.started} maxLength={10} placeholder="YYYY/MM/DD" inputMode="numeric" onChange={e=>setForm({...form,started:formatDateInput(e.target.value)})}/></label><label className="admin-field"><span>Ended</span><input value={form.ended} maxLength={10} placeholder="YYYY/MM/DD" inputMode="numeric" onChange={e=>setForm({...form,ended:formatDateInput(e.target.value)})}/></label><label className="admin-field"><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as AdminProjectStatus})}>{PROJECT_STATUSES.map(status=><option key={status} value={status}>{status}</option>)}</select></label></div>
 <div className="admin-project-section"><div className="admin-painting-section-title"><p className="admin-card-kicker">MEDIUM</p><span>{form.medium.length} selected</span></div><CategoryMultiSelect categories={categories} value={form.medium} onChange={(medium)=>setForm(f=>({...f,medium}))} /></div>
 <div className="admin-project-section"><div className="admin-painting-section-title"><p className="admin-card-kicker">LINKS</p><button type="button" className="admin-project-add" onClick={addLink}>+ Add link</button></div>{form.links.map((l,i)=><div className="admin-project-row" key={l.id}><input placeholder="Title" value={l.title} onChange={e=>setForm(f=>({...f,links:f.links.map((x,n)=>n===i?{...x,title:e.target.value}:x)}))}/><input placeholder="https://..." value={l.link} onChange={e=>setForm(f=>({...f,links:f.links.map((x,n)=>n===i?{...x,link:e.target.value}:x)}))}/><button type="button" onClick={()=>setForm(f=>({...f,links:f.links.filter((_,n)=>n!==i)}))}>×</button></div>)}</div>
 <div className="admin-project-section"><div className="admin-painting-section-title"><p className="admin-card-kicker">CUSTOM FIELDS</p><button type="button" className="admin-project-add" onClick={addField}>+ Add field</button></div>{form.dynamicFields.map((f,i)=><div className="admin-project-row" key={i}><input placeholder="Key" value={f.key} onChange={e=>setForm(x=>({...x,dynamicFields:x.dynamicFields.map((v,n)=>n===i?{...v,key:e.target.value}:v)}))}/><input placeholder="Value" value={f.value} onChange={e=>setForm(x=>({...x,dynamicFields:x.dynamicFields.map((v,n)=>n===i?{...v,value:e.target.value}:v)}))}/><button type="button" onClick={()=>setForm(x=>({...x,dynamicFields:x.dynamicFields.filter((_,n)=>n!==i)}))}>×</button></div>)}</div>
 <div className="admin-painting-form-actions"><button className="admin-submit" disabled={saving||storageLoading}>{saving?"Saving…":editing?"Save project":"Add project"} <span>↗</span></button></div></form>}
 {tab==="collection"&&<section className="admin-project-list"><div className="admin-painting-library-heading"><div><p className="admin-card-kicker">COLLECTION</p><h2>Projects</h2></div><span>{projects.length} results</span></div>{loading?<div className="admin-painting-skeleton"><span/></div>:!projects.length?<div className="admin-category-empty">No projects yet.</div>:projects.map((p,i)=><article className="admin-project-card" key={p.id}><div><span className="admin-project-index">{String(i+1).padStart(2,"0")}</span><h3>{p.title}</h3><p>{p.myRole}</p></div><div><span className="admin-project-status">{p.status}</span><small>{p.started}{p.ended?" → "+p.ended:""}</small></div><div className="admin-project-card-meta"><span>{p.medium.length} medium</span><span>{p.links.length} links</span><span>{Object.keys(p.dynamicFields).length} custom fields</span></div><div className="admin-project-card-actions"><button onClick={()=>startEdit(p)}>Edit</button><button onClick={()=>void remove(p.id)} disabled={saving}>Delete</button></div></article>)}</section>}
 {toast&&<div className={"admin-category-toast admin-category-toast--"+toast.type} role="status"><span>{toast.type==="success"?"✓":"!"}</span><p>{toast.text}</p><button onClick={()=>setToast(null)}>×</button></div>}</div></section></main>;
}