import { randomUUID } from "crypto";
import { getDatabase } from "@/lib/mongodb";
import type { AdminProjectStatus } from "@/interfaces/ProjectStatus";
const COLLECTION="admin_project_statuses";
const DEFAULTS=[{id:"done",name:"Done"},{id:"in-progress",name:"Inprogress"}];
async function ensureDefaults(){const c=(await getDatabase()).collection<AdminProjectStatus>(COLLECTION),now=new Date().toISOString();for(const item of DEFAULTS)await c.updateOne({id:item.id},{$setOnInsert:{...item,system:true,createdAt:now,updatedAt:now}},{upsert:true});}
export async function getProjectStatuses(){await ensureDefaults();return(await getDatabase()).collection<AdminProjectStatus>(COLLECTION).find({}).project({_id:0}).sort({system:-1,name:1}).toArray();}
export async function createProjectStatus(input:unknown){const name=normalizeName(input),db=await getDatabase();if(await db.collection<AdminProjectStatus>(COLLECTION).findOne({name:{$regex:"^"+escapeRegex(name)+"$",$options:"i"}}))throw new Error("A status with this name already exists.");const now=new Date().toISOString(),status={id:randomUUID(),name,system:false,createdAt:now,updatedAt:now};await db.collection<AdminProjectStatus>(COLLECTION).insertOne(status);return status;}
export async function updateProjectStatus(id:string,input:unknown){const name=normalizeName(input),db=await getDatabase(),current=await db.collection<AdminProjectStatus>(COLLECTION).findOne({id});if(!current)throw new Error("Status was not found.");if(current.system)throw new Error("Default statuses cannot be edited.");if(await db.collection<AdminProjectStatus>(COLLECTION).findOne({id:{$ne:id},name:{$regex:"^"+escapeRegex(name)+"$",$options:"i"}}))throw new Error("A status with this name already exists.");const updated={...current,name,updatedAt:new Date().toISOString()};await db.collection<AdminProjectStatus>(COLLECTION).replaceOne({id},updated);return updated;}
export async function deleteProjectStatus(id:string){const db=await getDatabase(),current=await db.collection<AdminProjectStatus>(COLLECTION).findOne({id});if(!current)throw new Error("Status was not found.");if(current.system)throw new Error("Default statuses cannot be deleted.");if(await db.collection("admin_projects").countDocuments({statusId:id}))throw new Error("This status is used by projects and cannot be deleted.");await db.collection<AdminProjectStatus>(COLLECTION).deleteOne({id});}
function normalizeName(value:unknown){if(typeof value!=="string")throw new Error("Status name is required.");const name=value.trim();if(!name)throw new Error("Status name is required.");if(name.length>60)throw new Error("Status name cannot exceed 60 characters.");return name;}
function escapeRegex(value:string){return value.replace(/[.*+?^()|[\\]\\]/g,"\\$&");}