import { randomUUID } from "crypto";
import { getDatabase } from "@/lib/mongodb";
import type { AdminProject } from "@/interfaces/Project";
const COLLECTION="admin_projects";
function text(value:unknown,label:string,required=false){if(typeof value!=="string"){if(!required&&(value===null||value===undefined))return "";throw new Error(label+" must be text.");}const result=value.trim();if(required&&!result)throw new Error(label+" is required.");if(result.length>5000)throw new Error(label+" is too long.");return result;}
function date(value:unknown,label:string,required=true){const result=text(value,label,required);if(result&&!/^\\d{4}\\/\\d{2}\\/\\d{2}$/.test(result))throw new Error(label+" must use YYYY/MM/DD format.");return result;}
function normalizeLinks(value:unknown){if(!Array.isArray(value))throw new Error("Links must be an array.");return value.map(item=>{const row=item as {id?:unknown;title?:unknown;link?:unknown};const title=text(row.title,"Link title",true),link=text(row.link,"Link URL",true);try{new URL(link);}catch{throw new Error("Every project link must be a valid URL.");}return{id:typeof row.id==="string"&&row.id?row.id:randomUUID(),title,link};});}
function normalizeFields(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Dynamic fields are invalid.");const result:Record<string,string>={};for(const [key,val] of Object.entries(value)){const k=key.trim();if(k)result[k]=text(val,"Value for "+k);}return result;}
function normalize(body:Record<string,unknown>,statusIds:Set<string>,current?:AdminProject):AdminProject{const title=text(body.title,"Title",true),myRole=text(body.myRole,"My Role",true),started=date(body.started,"Started",true),statusId=text(body.statusId,"Status",true);if(!statusIds.has(statusId))throw new Error("Selected status was not found.");const ended=date(body.ended,"Ended",false)||null,statusName=typeof body.statusName==="string"?body.statusName:"";if(statusName.toLowerCase()==="done"&&!ended)throw new Error("Ended is required when status is Done.");const medium=Array.isArray(body.medium)?body.medium.filter((x):x is string=>typeof x==="string"&&x.trim()).map(x=>x.trim()):[];if(!medium.length)throw new Error("At least one medium category is required.");const now=new Date().toISOString();return{id:current?.id??randomUUID(),title,myRole,started,ended,medium,statusId,links:normalizeLinks(body.links),dynamicFields:normalizeFields(body.dynamicFields??{}),createdAt:current?.createdAt??now,updatedAt:now};}
export async function getProjects(){return(await getDatabase()).collection<AdminProject>(COLLECTION).find({}).project({_id:0}).sort({updatedAt:-1}).toArray();}
export async function createProject(body:Record<string,unknown>,statusIds:Set<string>){const db=await getDatabase(),project=normalize(body,statusIds);await db.collection<AdminProject>(COLLECTION).insertOne(project);return project;}
export async function updateProject(id:string,body:Record<string,unknown>,statusIds:Set<string>){const db=await getDatabase(),current=await db.collection<AdminProject>(COLLECTION).findOne({id});if(!current)throw new Error("Project was not found.");const project=normalize(body,statusIds,current);await db.collection<AdminProject>(COLLECTION).replaceOne({id},project);return project;}
export async function deleteProject(id:string){const result=await(await getDatabase()).collection<AdminProject>(COLLECTION).deleteOne({id});if(!result.deletedCount)throw new Error("Project was not found.");}