import type { PortfolioData } from '@/interfaces/Portfolio';

// Temporary content only. Replace this object with the admin/API response later.
// Medium IDs are references to administrator-defined categories, not an enum.
export const fakeData: PortfolioData = {
  artist: { name: 'GHAZAL SHAFIEI', description: 'A multidisciplinary artist working across painting, illustration, animation and design.' },
  mediums: [{ id: 'charcoal', label: 'Charcoal' }, { id: 'digital-painting', label: 'Digital Painting' }],
  paintingCategories: [
    { id: 'charcoal', label: 'Charcoal' },
    { id: 'digital-painting', label: 'Digital Painting' },
    {
      id: 'series',
      label: 'Series',
      children: [
        { id: 'roxy-series', label: 'Roxy' },
        { id: 'table-series', label: 'Table Studies' },
      ],
    },
  ],
  artworks: [
    { id: 'still-life', title: 'Still Life in Shadow', year: 2023, createdAt: '2023-04-12', mediumId: 'digital-painting', paintingCategoryIds: ['digital-painting', 'table-series'], description: 'A study of light, everyday objects and negative space.', dimensions: '3000 × 4000 px', image: { src: '/artworks/artwork-13.png', alt: 'Black and white still life with a hanging lamp and folded fabric', width: 840, height: 1121, flipX: true }, table: { rotation: -10, aspectRatio: 0.75 } },
    { id: 'table-study', title: 'Table Study', year: 2022, createdAt: '2022-09-08', mediumId: 'digital-painting', paintingCategoryIds: ['digital-painting', 'table-series'], description: 'An observational composition in black and white.', dimensions: '3000 × 4000 px', image: { src: '/artworks/artwork-7.png', alt: 'A monochrome study of a plate and objects on a table', width: 841, height: 1122 }, table: { rotation: -12.96, aspectRatio: 0.75 } },
    { id: 'in-transit', title: 'In Transit', year: 2024, createdAt: '2024-02-16', mediumId: 'charcoal', paintingCategoryIds: ['charcoal'], description: 'An exploratory line study based on original photography.', dimensions: '3000 × 4000 px', image: { src: '/artworks/artwork-16.png', alt: 'An intricate line drawing of a quiet moment inside a vehicle', width: 840, height: 1121, flipX: true }, table: { rotation: 10, aspectRatio: 0.75 } },
    { id: 'floating', title: 'Floating', year: 2025, createdAt: '2025-07-03', mediumId: 'digital-painting', paintingCategoryIds: ['digital-painting'], description: 'A figure suspended in water, light and colour.', dimensions: '4000 × 3000 px', image: { src: '/images/5.jpg', alt: 'A painted figure floating in turquoise water', width: 4000, height: 3000, rotate: -90 }, table: { rotation: 10, aspectRatio: 1.334 } },
    { id: 'at-the-table', title: 'At the Table', year: 2023, createdAt: '2023-11-20', mediumId: 'digital-painting', paintingCategoryIds: ['digital-painting', 'table-series'], description: 'A shadow-pass study of a plate and cutlery.', dimensions: '3000 × 4000 px', image: { src: '/artworks/artwork-6.png', alt: 'Black and white painting of a plate, fork and knife', width: 838, height: 1120 }, table: { rotation: 0, aspectRatio: 0.748 } },
    { id: 'roxy-line-study', title: 'Roxy — Line Study', year: 2024, createdAt: '2024-05-09', mediumId: 'charcoal', paintingCategoryIds: ['charcoal', 'roxy-series'], description: 'The original line study for Roxy On A Ride.', dimensions: '3000 × 4000 px', image: { src: '/artworks/artwork-12.png', alt: 'A line drawing of a cat riding in a car', width: 840, height: 1121 }, table: { rotation: 14.96, aspectRatio: 0.75 } },
    { id: 'roxy-on-a-ride', title: 'Roxy On A Ride', year: 2024, createdAt: '2024-06-18', mediumId: 'digital-painting', paintingCategoryIds: ['digital-painting', 'roxy-series'], description: 'Digital Painting based on Original Photography, shadow pass', dimensions: '3000*4000px', image: { src: '/artworks/artwork-19.png', alt: 'Roxy the cat beside a steering wheel, rendered in bold black and white', width: 846, height: 1120, flipX: true }, table: { rotation: 0, aspectRatio: 0.7554 } },
  ],
  projects: [
    {
      id: 'salt-and-water',
      name: 'Salt & Water',
      tagline: 'A painting series that follows one summer of swimming, salt and sand.',
      description: 'Four canvases built from photographs taken on the same coastline: a body suspended in water, shells arranged by the tide and the quiet weight of a long afternoon. The series studies how colour survives in a memory of light.',
      year: 2025,
      discipline: 'Painting Series',
      client: 'Self-initiated',
      myRole: ['Painting', 'Photography', 'Series Editing'],
      cover: {
        src: '/images/5.jpg',
        alt: 'A painted figure suspended in turquoise water seen from above',
        width: 3024,
        height: 4032,
        aspectRatio: 0.75,
        caption: 'Floating — one of the four paintings in the series.',
      },
      gallery: [
        {
          src: '/images/6.jpg',
          alt: 'Four pale shells arranged symmetrically on coarse wet sand',
          width: 3024,
          height: 4032,
          aspectRatio: 0.75,
          caption: 'Reference photograph: shells arranged by the tide, used for the palette study.',
        },
        {
          src: '/images/2.jpg',
          alt: 'Fine line drawing of a plate of food with a handwritten note reading I want pizza for my birthday',
          width: 3024,
          height: 4032,
          aspectRatio: 0.75,
          caption: 'Warm-up line study kept from the same sketchbook.',
        },
      ],
      links: [
        { id: 'series-notes', label: 'Series Notes', href: 'https://example.com/salt-and-water' },
      ],
      dynamicFields: {
        Format: 'Four canvases, 120 × 90 cm each',
        Medium: 'Oil on linen',
        Tools: 'Photography, digital colour studies, oil',
        Status: 'Completed',
      },
    },
    {
      id: 'roxy-on-a-ride',
      name: 'Roxy On A Ride',
      tagline: 'A wordless picture book about a cat who takes the wheel.',
      description: 'The story is told entirely through the passenger window. Beginning as a loose line study of a car interior, the book moves through the shadow pass into bold black and white spreads, keeping the cat as the only solid shape in every frame.',
      year: 2024,
      discipline: 'Illustrated Book',
      client: 'Independent publication',
      myRole: ['Illustration', 'Storyboarding', 'Character Design'],
      cover: {
        src: '/artworks/artwork-19.png',
        alt: 'Roxy the cat sitting beside a steering wheel in bold black and white',
        width: 846,
        height: 1120,
        aspectRatio: 0.7554,
        caption: 'Digital Painting based on Original Photography, shadow pass',
      },
      gallery: [
        {
          src: '/artworks/artwork-12.png',
          alt: 'Line drawing of a cat riding in a car, the original study for the book',
          width: 841,
          height: 1122,
          aspectRatio: 0.75,
          caption: 'Original line study for the cover spread.',
        },
        {
          src: '/images/3.jpg',
          alt: 'Detailed line drawing of a car interior seen through the windscreen',
          width: 3024,
          height: 4032,
          aspectRatio: 0.75,
          caption: 'Interior reference drawn from the passenger seat before the shapes were reduced.',
        },
      ],
      links: [
        { id: 'book', label: 'The Book', href: 'https://example.com/roxy-on-a-ride' },
        { id: 'process', label: 'Process', href: 'https://example.com/roxy-on-a-ride/process' },
      ],
      dynamicFields: {
        Format: '32 pages, 240 × 240 mm',
        Medium: 'Charcoal study, digital shadow pass',
        Edition: 'First print run, 500 copies',
        Status: 'Published',
      },
    },
    {
      id: 'in-the-room',
      name: 'In The Room',
      tagline: 'Interiors drawn from life, from a sofa, a kitchen table and a busy bar.',
      description: 'A drawing diary of everyday rooms. Each sheet is finished in one sitting, so the mistakes stay in: the hem of a curtain that had already moved, a chair resting on the wrong line. The series is about attention rather than accuracy.',
      year: 2024,
      discipline: 'Drawing Series',
      client: 'Self-initiated',
      myRole: ['Drawing', 'Series Curation', 'Print Production'],
      cover: {
        src: '/images/4.jpg',
        alt: 'Line drawing of a person curled on a sofa, seen from behind',
        width: 919,
        height: 1225,
        aspectRatio: 0.75,
        caption: 'Sofa — drawn across a single afternoon without leaving the seat.',
      },
      gallery: [
        {
          src: '/images/7.jpg',
          alt: 'High contrast ink study of a figure leaning back in a well-lit room',
          width: 919,
          height: 1225,
          aspectRatio: 0.75,
          caption: 'Ink shadow pass made from the pencil sheet.',
        },
        {
          src: '/artworks/artwork-13.png',
          alt: 'Black and white still life with a hanging lamp and folded fabric',
          width: 841,
          height: 1122,
          aspectRatio: 0.75,
          caption: 'The lamp in the corner of the same room.',
        },
        {
          src: '/artworks/artwork-16.png',
          alt: 'Intricate line drawing of a quiet moment inside a busy bar',
          width: 840,
          height: 1121,
          aspectRatio: 0.75,
          caption: 'Back room of a bar, drawn standing up.',
        },
      ],
      links: [
        { id: 'diary', label: 'Drawing Diary', href: 'https://example.com/in-the-room' },
      ],
      dynamicFields: {
        Format: 'Eighteen sheets, 420 × 297 mm',
        Medium: 'Graphite and ink on paper',
        Exhibited: 'Group show, Tehran, 2024',
        Status: 'Ongoing',
      },
    },
    {
      id: 'table-studies',
      name: 'Table Studies',
      tagline: 'An observational drawing series about plates, cutlery and the people around them.',
      description: 'Every sheet starts as a plate and ends up being about the meal. High contrast shadow passes turn the cutlery into architecture, while the loose line drawings keep the noise of a full restaurant on the page.',
      year: 2023,
      discipline: 'Observational Drawing',
      client: 'Private commission',
      myRole: ['Drawing', 'Art Direction', 'Print Production'],
      cover: {
        src: '/artworks/artwork-6.png',
        alt: 'Black and white painting of a plate, fork and knife in high contrast shadow',
        width: 838,
        height: 1120,
        aspectRatio: 0.748,
        caption: 'Shadow pass built from a pencil study made at the table.',
      },
      gallery: [
        {
          src: '/images/2.jpg',
          alt: 'Fine line drawing of a plate of food beside a handwritten birthday note',
          width: 3024,
          height: 4032,
          aspectRatio: 0.75,
          caption: 'The note was already on the table, so it stayed in the drawing.',
        },
        {
          src: '/images/1.png',
          alt: 'High contrast black and white study of a plate with a fork and knife',
          width: 143,
          height: 190,
          aspectRatio: 0.75,
          caption: 'First shadow pass, later scaled up for the final print.',
        },
        {
          src: '/artworks/artwork-7.png',
          alt: 'Monochrome study of a plate and objects on a table',
          width: 841,
          height: 1123,
          aspectRatio: 0.75,
          caption: 'Companion sheet from the same sitting.',
        },
      ],
      links: [
        { id: 'prints', label: 'Prints', href: 'https://example.com/table-studies' },
        { id: 'commission', label: 'Commission', href: 'https://example.com/table-studies/commission' },
      ],
      dynamicFields: {
        Format: 'Six prints, 500 × 700 mm',
        Medium: 'Graphite, then digital shadow pass',
        Tools: 'Charcoal pencil, Photoshop',
        Status: 'Delivered',
      },
    },
  ],
};
