import { ArtTypes, IArts } from "@/interfaces";

export const fakeArts: IArts[] = [
  {
    id: 1,
    title: "Artwork 1",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/1.png",
  },
  {
    id: 2,
    title: "Artwork 2",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/2.jpg",
  },
  {
    id: 3,
    title: "Artwork 3",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/3.jpg",
  },
  {
    id: 4,
    title: "Artwork 4",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/4.jpg",
  },
  {
    id: 5,
    title: "Artwork 5",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/5.jpg",
  },
  {
    id: 6,
    title: "Artwork 6",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/6.jpg",
  },
  {
    id: 7,
    title: "Artwork 7",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/7.jpg",
  },
  {
    id: 8,
    title: "Artwork 8",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/1.png",
  },
  {
    id: 9,
    title: "Artwork 9",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/2.jpg",
  },
  {
    id: 10,
    title: "Artwork 10",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/3.jpg",
  },
  {
    id: 11,
    title: "Artwork 11",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/4.jpg",
  },
  {
    id: 12,
    title: "Artwork 12",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/5.jpg",
  },
  {
    id: 13,
    title: "Artwork 13",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/6.jpg",
  },
  {
    id: 14,
    title: "Artwork 14",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/7.jpg",
  },
  {
    id: 15,
    title: "Artwork 15",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/1.png",
  },
  {
    id: 16,
    title: "Artwork 16",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/2.jpg",
  },
  {
    id: 17,
    title: "Artwork 17",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/3.jpg",
  },
  {
    id: 18,
    title: "Artwork 18",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/4.jpg",
  },
  {
    id: 19,
    title: "Artwork 19",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/5.jpg",
  },
  {
    id: 20,
    title: "Artwork 20",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/6.jpg",
  },
  {
    id: 21,
    title: "Artwork 21",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/7.jpg",
  },
  {
    id: 22,
    title: "Artwork 22",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/1.png",
  },
  {
    id: 23,
    title: "Artwork 23",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/2.jpg",
  },
  {
    id: 24,
    title: "Artwork 24",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/3.jpg",
  },
  {
    id: 25,
    title: "Artwork 25",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/4.jpg",
  },
  {
    id: 26,
    title: "Artwork 26",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/5.jpg",
  },
  {
    id: 27,
    title: "Artwork 27",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/6.jpg",
  },
  {
    id: 28,
    title: "Artwork 28",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/7.jpg",
  },
  {
    id: 29,
    title: "Artwork 29",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/1.png",
  },
  {
    id: 30,
    title: "Artwork 30",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/2.jpg",
  },
  {
    id: 31,
    title: "Artwork 31",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/3.jpg",
  },
  {
    id: 32,
    title: "Artwork 32",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/4.jpg",
  },
  {
    id: 33,
    title: "Artwork 33",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/5.jpg",
  },
  {
    id: 34,
    title: "Artwork 34",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/6.jpg",
  },
  {
    id: 35,
    title: "Artwork 35",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/7.jpg",
  },
  {
    id: 36,
    title: "Artwork 36",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/1.png",
  },
  {
    id: 37,
    title: "Artwork 37",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/2.jpg",
  },
  {
    id: 38,
    title: "Artwork 38",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/3.jpg",
  },
  {
    id: 39,
    title: "Artwork 39",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "painting",
    uri: "/images/4.jpg",
  },
  {
    id: 40,
    title: "Artwork 40",
    description: "A beautiful piece of art",
    type: ArtTypes.IMG,
    category: "sketch",
    uri: "/images/5.jpg",
  },
];
